### ISSUE TITLE
java.lang.NullPointerException after Updating to Lucee 5.2

### ISSUE THREAD

**Issue by Meikelv** [boughtonp/cfpassphrase#21]
Hi,
after updating my lucee version to 5.2.0.1-SNAPSHOT I got the following error:
lucee.runtime.exp.NativeException: java.lang.NullPointerException
 	at lucee.runtime.exp.NativeException.newInstance(NativeException.java:69)
 	at lucee.runtime.op.Caster.toPageException(Caster.java:3186)
 	at lucee.runtime.op.CastImpl.toPageException(CastImpl.java:700)
 	at sorcerersisle.cfpassphrase.lucee.PassphraseHash.call(PassphraseHash.java:51)
 	at sorcerersisle.cfpassphrase.lucee.PassphraseHash.call(PassphraseHash.java:27)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at lucee.runtime.reflection.pairs.MethodInstance.invoke(MethodInstance.java:55)
 	at lucee.runtime.reflection.Reflector.callStaticMethod(Reflector.java:920)
 	at lucee.runtime.functions.BIFProxy.invoke(BIFProxy.java:41)
 	at lucee.runtime.tag.TagUtil.invokeBIF(TagUtil.java:343)
 	at hepatitis_c_register990.indexframe_cfm$cf.call(/hepatitis-c-register/indexframe.cfm:49)
 	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:918)
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:833)
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:828)
 	at lucee.runtime.listener.ClassicAppListener._onRequest(ClassicAppListener.java:62)
 	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)
 	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2293)
 	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2284)
 	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2252)
 	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:891)
 	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
 	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62)
 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
 	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:476)
 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 	at java.lang.Thread.run(Thread.java:745) 

Is there a new version of cfpassphrase?

Thank you

Michael

**Comment by Meikelv** [comment]
Don't know why and how, but I reinstalled lucee, now with newer snapshot (5.2.0.4) and copied the osgi-bundle (cfpassphrase-bundle.jar) to c:\lucee\tomcat\lucee-server\bundles\ and the fld after editing (<class> to <class bundle-name="sorcerersisle.cfpassphrase" bundle-version="0.1">) into c:\lucee\tomcat\lucee-server\context\library\fld\ and the tld to c:\lucee\tomcat\lucee-server\context\library\tld\ and now **it works!!!**

Thank you very much!

**Comment by andrew-dixon** [comment]
Try the extension version I've created and you can download from here:

https://s3-eu-west-1.amazonaws.com/cfpassphrase/cfpassphrase.lex

I've tried it with the latest Lucee 5 release and it worked fine.

**Comment by boughtonp** [comment]
See #20 - closing this as duplicate.
